CREATE TABLE User (
Id        INTEGER PRIMARY KEY NOT NULL,
Username  VARCHAR NOT NULL,
First_name VARCHAR NOT NULL,
Last_name  VARCHAR NOT NULL,
Email      VARCHAR NOT NULL,
Password   VARCHAR NOT NULL
);
